name: Build Artifact

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: redis-grpc
          path: target/release/redis-grpc