name: Publish Docker Image

on:
  release:
    types: [created]

jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: roytang121/redis-grpc:${{ steps.get_release.outputs.tag_name }},roytang121/redis-grpc:latest

  publish-npm:
    needs: publish-docker-hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./proto
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: gen-js
        working-directory: ./
        run: docker-compose -f "docker-compose.yaml" run --rm gen-js
      - name: publish-npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}