name: Publish NPM Packages

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./proto
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: gen-js
        working-directory: ./
        run: docker-compose -f "docker-compose.yaml" run --rm gen-js
      - name: publish-npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
